version: '3'

services:
  django-db:
    container_name: backend-django-db
    restart: always
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - base
    env_file: .env
    volumes:
      - ./mysql-data:/var/lib/mysql

  django-app:
    container_name: backend-django-app
    restart: always
    build: backend
    links:
      - django-db
    command: sh ./startup.sh
    env_file: .env
    networks:
      - base
    volumes:
      - ./backend:/personal_site_app
      - web-static:/personal_site_app/static
      - media:/personal_site_app/media
    ports:
      - "8000:8000"
  svelte-app:
    container_name: frond-end-svelte
    restart: always
    build: front-end
    links:
      - django-app
    command: sh ./startup.sh
    env_file: .env
    networks:
      - base
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/front-end/
  nginx:
    container_name: nginx
    restart: always
    build: nginx
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
      - media:/www/media
    links:
      - django-app
    depends_on:
      - django-app
    networks:
      - base

networks:
  base:

volumes:
  web-static:
  media:

